name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]  # Ensure this exactly matches your CI workflow name.
    types:
      - completed
  workflow_dispatch: {}  # Enables a manual trigger button.

jobs:
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Release Binary
        run: cargo build --release

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --no-verify
